
experiment_name:
  Auto_config
set_seed:
  False
pytorch_seed:
  2021
data:
  eeg
num_classes:
  2
feature_list:
  - 16
  - 128
  - 256
  - 512
size_list:
  - 32
  - 32
  - 16
  - 8
hidden_size_list:
  - 128
  - 128
  - 128
push_nums_list:
  - 2
  - 2
  - 2
mult_k:
  1
densenetparameter:
  feature_list:
    - - 16
      - 16
      - 16
      - 16
    - - 32
      - 32
      - 32
      - 32
  bn_size:
    2
  drop_rate:
    0.1
  use_size_change:
    False
parameters:
  # default parameters
  loss_option:
    smooth_cross
  push_num:
    3
  s:
    1
  length:
    25
  tmp_feature:
    28
  sigma:
    0.1
  batch_size:
    16
  epoch:
    400
  dropout:
    0.5
  filter_tau_m:
    4
  filter_tau_s:
    1
  train_coefficients:
    True
  train_bias:
    True
  membrane_filer:
    False
shape: [[2,2,2]]
optimizer:
  optimizer_choice:
    'SGD'
  Adam:
    lr: 0.001
    weight_decay: 0
  AdamW:
    lr: 0.005
    weight_decay: 1e-4
  SAM:
    lr: 0.005
    weight_decay: 1e-4
  SGD:
    momentum: 0.9
    lr: 0.05
    weight_decay: 0
  ASGD:
    lr: 0.0001
    weight_decay: 1e-4
  Rprop:
    lr: 0.0001
    etas: (0.5,1.5)


scheduler:
  scheduler_choice:
    'SchedulerLR'
  SchedulerLR:
    milestones:
      - 0.9
    gamma:
      0.1
  MultiStepLR:
    milestones:
      - 25
      - 35
    gamma:
      0.1
  CosineAnnealingWarmRestarts:
    T_0:
      1000
  CyclicLR:
    base_lr:
      0.0001
    max_lr:
      0.001
    step_size_up:
      2000

transform:
  RandomResizedCrop:
    size:
      28
    scale:
      - 0.85
      - 1.0
    ratio:
      - 0.75
      - 1.3333333333333333
    interpolation:
      2
  RandomRotation:
    angle:
      15
  RandomApply:
    probability:
      0.5

mnist_config:
  max_rate:
    1
  use_transform:
    True
output:
  ./output